apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrichment
spec:
  selector:
    matchLabels:
      app: enrichment
  replicas: 2
  template:
    metadata:
      labels:
        app: enrichment
    spec:
      containers:
      - name: enrichment
        image: enrichment:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 5
